//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCaster.Alarm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyCaster.Alarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        internal static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic connect to the Telegram.
        /// </summary>
        internal static string AutomaticConnect {
            get {
                return ResourceManager.GetString("AutomaticConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call web hook (url).
        /// </summary>
        internal static string CallWebHook {
            get {
                return ResourceManager.GetString("CallWebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit the application?.
        /// </summary>
        internal static string ConfirmCloseApplication {
            get {
                return ResourceManager.GetString("ConfirmCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the exception?.
        /// </summary>
        internal static string ConfirmDeleteExclusion {
            get {
                return ResourceManager.GetString("ConfirmDeleteExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete a message?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the schedule?.
        /// </summary>
        internal static string ConfirmDeleteTask {
            get {
                return ResourceManager.GetString("ConfirmDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop message processing?.
        /// </summary>
        internal static string ConfirmStopWork {
            get {
                return ResourceManager.GetString("ConfirmStopWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email verification code:.
        /// </summary>
        internal static string EnterEmailVerificationCode {
            get {
                return ResourceManager.GetString("EnterEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number:.
        /// </summary>
        internal static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the required value.
        /// </summary>
        internal static string EnterRequiredValue {
            get {
                return ResourceManager.GetString("EnterRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code:.
        /// </summary>
        internal static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude messages.
        /// </summary>
        internal static string ExcludeMessages {
            get {
                return ResourceManager.GetString("ExcludeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeea (s).
        /// </summary>
        internal static string ExecuteEvery {
            get {
                return ResourceManager.GetString("ExecuteEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe;*.cmd;*.bat;*.com)|*.exe;*.cmd;*.bat;*.com&quot;.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find text.
        /// </summary>
        internal static string FindText {
            get {
                return ResourceManager.GetString("FindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level:.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message History.
        /// </summary>
        internal static string MessageHistory {
            get {
                return ResourceManager.GetString("MessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message #.
        /// </summary>
        internal static string MessageNumber {
            get {
                return ResourceManager.GetString("MessageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages and Actions.
        /// </summary>
        internal static string MessagesAndActions {
            get {
                return ResourceManager.GetString("MessagesAndActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! New message!.
        /// </summary>
        internal static string NewMessageWarning {
            get {
                return ResourceManager.GetString("NewMessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - there are no messages to process.
        /// </summary>
        internal static string NoNessagesToProcess {
            get {
                return ResourceManager.GetString("NoNessagesToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the primary telegram channel is not specified.
        /// </summary>
        internal static string NoPrimaryTelegramChannel {
            get {
                return ResourceManager.GetString("NoPrimaryTelegramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - no telegram channels specified.
        /// </summary>
        internal static string NoTelegramChannels {
            get {
                return ResourceManager.GetString("NoTelegramChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other settings.
        /// </summary>
        internal static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (if required).
        /// </summary>
        internal static string PasswordIfExissts {
            get {
                return ResourceManager.GetString("PasswordIfExissts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid code.
        /// </summary>
        internal static string PHONE_CODE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number banned.
        /// </summary>
        internal static string PHONE_NUMBER_BANNED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have deleted and re-created your account too many times recently. Please wait for a few days before signing up again.
        /// </summary>
        internal static string PHONE_NUMBER_FLOOD {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_FLOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number. Please try again.
        /// </summary>
        internal static string PHONE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number.
        /// </summary>
        internal static string PleaseEnterPhone {
            get {
                return ResourceManager.GetString("PleaseEnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press EDIT to change configuration.
        /// </summary>
        internal static string PressEDIT {
            get {
                return ResourceManager.GetString("PressEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press key.
        /// </summary>
        internal static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SAVE or CANCEL to end editing.
        /// </summary>
        internal static string PressSAVEorCANCEL {
            get {
                return ResourceManager.GetString("PressSAVEorCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary channel description.
        /// </summary>
        internal static string PrimaryChannelDescription {
            get {
                return ResourceManager.GetString("PrimaryChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary channel.
        /// </summary>
        internal static string PrimaryСhannel {
            get {
                return ResourceManager.GetString("PrimaryСhannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process list:.
        /// </summary>
        internal static string ProcessList {
            get {
                return ResourceManager.GetString("ProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this configuration?.
        /// </summary>
        internal static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save messages to (path).
        /// </summary>
        internal static string SaveMessagesTo {
            get {
                return ResourceManager.GetString("SaveMessagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving configuration error ({0}).
        /// </summary>
        internal static string SavingConfigurationError {
            get {
                return ResourceManager.GetString("SavingConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule actions.
        /// </summary>
        internal static string ScheduleActions {
            get {
                return ResourceManager.GetString("ScheduleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - since the messages are not specified, the schedule will not work.
        /// </summary>
        internal static string ScheduleWillNotWork {
            get {
                return ResourceManager.GetString("ScheduleWillNotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select executable file.
        /// </summary>
        internal static string SelectExecutableFile {
            get {
                return ResourceManager.GetString("SelectExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process.
        /// </summary>
        internal static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application when Windows starts.
        /// </summary>
        internal static string StartApplication {
            get {
                return ResourceManager.GetString("StartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopMessage {
            get {
                return ResourceManager.GetString("StopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram account settings.
        /// </summary>
        internal static string TelegramAccount {
            get {
                return ResourceManager.GetString("TelegramAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram account setup.
        /// </summary>
        internal static string TelegramAccountSetup {
            get {
                return ResourceManager.GetString("TelegramAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram channels.
        /// </summary>
        internal static string TelegramChannels {
            get {
                return ResourceManager.GetString("TelegramChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram connection state - .
        /// </summary>
        internal static string TelegramConnectionState {
            get {
                return ResourceManager.GetString("TelegramConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Login.
        /// </summary>
        internal static string TelegramLogin {
            get {
                return ResourceManager.GetString("TelegramLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test channel.
        /// </summary>
        internal static string TestChannel {
            get {
                return ResourceManager.GetString("TestChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test channel description.
        /// </summary>
        internal static string TestChannelDescription {
            get {
                return ResourceManager.GetString("TestChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing.
        /// </summary>
        internal static string TestError {
            get {
                return ResourceManager.GetString("TestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following warnings were found:.
        /// </summary>
        internal static string WarningsFound {
            get {
                return ResourceManager.GetString("WarningsFound", resourceCulture);
            }
        }
    }
}
